{{- if .Values.backups.enabled -}}
apiVersion: batch/v1
kind: CronJob
metadata:
  name: create-backup
  namespace: {{ .Release.Namespace }}
spec:
  schedule: {{ .Values.backups.schedule | quote}}
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            rondbService: {{ include "rondb.labels.rondbService.create-backup" $ }}
        spec:
{{- include "rondb.SecurityContext" $ | indent 10 }}
          serviceAccountName: rondb-backups-sa
          restartPolicy: OnFailure
          initContainers:
{{ include "rondb.apiInitContainer" . | indent 10 }}
          - name: backup-metadata
            image: {{ include "rondb.toolboxImage" (dict "Values" .Values "default" .default "image" .Values.images.toolbox) }}
            imagePullPolicy: {{ include "hopsworkslib.imagePullPolicy" . | default "IfNotPresent" }}
            command:
            - /bin/bash
            - -c
            - |
{{ tpl (.Files.Get "files/scripts/backups/metadata_upload_kubectl.sh") . | indent 14 }}
            env:
            - name: JOB_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: MYSQLD_PODNAME
              value: {{ include "rondb.mysqldPodname" . }}
            # On MySQLd Pod:
            - name: REMOTE_BACKUP_DIR
              value: /tmp/backup
            - name: LOCAL_BACKUP_DIR
              value: /home/hopsworks/schemata
            - name: RCLONE_MOUNT_FILEPATH
              value: &rawRCloneConf /home/hopsworks/rclone-raw.conf
            # This will be read by rclone
            - name: RCLONE_CONFIG
              value: /home/hopsworks/rclone.conf
{{- if eq $.Values.backups.objectStorageProvider "s3" }}
            - name: ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
{{- toYaml .Values.backups.s3.keyCredentialsSecret | nindent 18 }}
                  optional: true
            - name: SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
{{- toYaml .Values.backups.s3.secretCredentialsSecret | nindent 18 }}
                  optional: true
{{- end }}
            volumeMounts:
            - name: rclone-configs
              mountPath: *rawRCloneConf
              subPath: rclone.conf
          # RonDB contains a native backup protocol, which is launched through
          # the mgm client. It essentially causes every datanode to create a binary
          # backup that it stores locally.
          - name: run-native-backup
            image: {{ include "image_address" (dict "image" .Values.images.rondb) }}
            imagePullPolicy: {{ include "hopsworkslib.imagePullPolicy" . | default "IfNotPresent" }}
            command:
            - /bin/bash
            - -c
            - |
              JOB_NUMBER=$(echo $JOB_NAME | tr -d '[[:alpha:]]' | tr -d '-' | sed 's/^0*//' | cut -c -9)
              ndb_mgm --ndb-connectstring=$MGM_CONNECTSTRING -e "START BACKUP $JOB_NUMBER SNAPSHOTEND WAIT COMPLETED"
            env:
            - name: JOB_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: MGM_CONNECTSTRING
              value: {{ include "rondb.mgmdHostname" . }}:1186
          containers:
          - name: upload-native-backups
            image: {{ include "rondb.toolboxImage" (dict "Values" .Values "default" .default "image" .Values.images.toolbox) }}
            imagePullPolicy: {{ include "hopsworkslib.imagePullPolicy" . | default "IfNotPresent" }}
            workingDir: /home/hopsworks
            command:
            - /bin/bash
            - -c
            - |
{{ tpl (.Files.Get "files/scripts/backups/native_upload_kubectl.sh") . | indent 14 }}
            env:
            - name: JOB_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
          volumes:
          - name: rclone-configs
            configMap:
              name: rclone-configs
---
{{- end -}}
