# Copyright (c) 2024-2025 Hopsworks AB. All rights reserved.

{{ if or (include "rondb.backups.isEnabled" .) (include "rondb.restoreFromBackup.backupId" .) }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: rclone-configs
  namespace: {{ .Release.Namespace }}
data:
    rclone.conf: |
        [{{ include "rondb.rcloneRestoreRemoteName" . }}]
{{ include "rondb.rcloneConfig" (dict "backupConfig" .Values.restoreFromBackup "global" .Values.global) | nindent 8}}

        [{{ include "rondb.rcloneBackupRemoteName" . }}]
{{ include "rondb.rcloneConfig" (dict "backupConfig" .Values.backups "global" .Values.global) | nindent 8}}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: rondb-backups-rb
  namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: rondb-backups-role
subjects:
  - kind: ServiceAccount
    name: rondb-backups-sa
    namespace: {{ .Release.Namespace }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: rondb-backups-sa
  namespace: {{ .Release.Namespace }}
{{ include "rondb.serviceAccountAnnotations" $ | indent 2 }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: rondb-backups-role
  namespace: {{ .Release.Namespace }}
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get"]
  - apiGroups: [""]
    resources: ["pods/exec"]
    verbs: ["create"]
    resourceNames:
{{- range $nodeGroup := until ($.Values.clusterSize.numNodeGroups | int) }}
{{- range $replica := until 3 }}
    - node-group-{{ $nodeGroup }}-{{ $replica }}
{{- end }}
{{- end }}
    - {{ include "rondb.mysqldPodname" . }}
{{- if include "rondb.backups.metadataStore.configMapName" $ }}
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["create", "get", "list", "patch"]
{{- end }}
{{- end }}
