CREATE TABLE t6 (
    id INT NOT NULL,
    fid_t2 INT NOT NULL,
    date DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
    str VARCHAR(500) NOT NULL,
    PRIMARY KEY (id),
    UNIQUE KEY k_fid_t2 (fid_t2)
) TABLESPACE ts_1 STORAGE DISK ENGINE = NDB;
